version: '3'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: yugioh
      DB_USER: root
      DB_PASSWORD: password
      DB_HOST: 172.18.0.2
      DB_PORT: 3306
      DB_NAME: yugioh

